{% set name = "microsoft-kiota-authentication-azure" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_authentication_azure-{{ version }}.tar.gz
  sha256: 6bb3b172644ceefcf73c01b5ec34a10a0cf27384af7f12b3f24c187111b38372

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.8.0
    - azure-core >=1.21.1
    - microsoft-kiota-abstractions
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_authentication_azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-authentication-azure-python
  summary: Authentication provider for Kiota using Azure Identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-authentication-azure-python
  doc_url: https://github.com/microsoft/kiota-authentication-azure-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
