{% set name = "microsoft-kiota-authentication-azure" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_authentication_azure-{{ version }}.tar.gz
  sha256: 9315074c10f84144b73897cb98baf84d215fe4271391fd1230c9ac9764122461

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - aiohttp >=3.8.0
    - azure-core >=1.21.1
    - microsoft-kiota-abstractions
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_authentication_azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/authentication/azure
  summary: Authentication provider for Kiota using Azure Identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/authentication/azure
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/authentication/azure/README.md

extra:
  recipe-maintainers:
    - xylar
